"""
WeekendPlanState — the central TypedDict flowing through the LangGraph graph.

Every agent receives the full state and returns a partial dict update.
LangGraph merges updates via the Annotated reducers below.

IMPORTANT: This is a TypedDict, NOT a Pydantic model.
Access fields with state["field"], never state.field.
"""

from __future__ import annotations

from datetime import date
from typing import Annotated, Literal

from typing_extensions import TypedDict

from nexus.state.reducers import append_log, append_to_list, merge_verdicts
from nexus.state.schemas import (
    ActivityProposal,
    AgentVerdict,
    FamilyActivity,
    FamilyProfile,
    PlanRequirements,
    RestaurantRecommendation,
    UserProfile,
)


class WeekendPlanState(TypedDict, total=False):
    """
    Full planning state that flows through the LangGraph StateGraph.

    LangGraph Pattern: TypedDict as graph state. Annotated fields use
    custom reducers for multi-writer merging. Non-annotated fields use
    last-write-wins semantics.

    Field naming follows snake_case throughout. All dict-access in agents.
    """

    # ── Core request context ──────────────────────────────────────────────────
    request_id: str
    user_intent: str
    target_date: date
    user_profile: UserProfile
    family_profile: FamilyProfile

    # ── Planning artifacts ────────────────────────────────────────────────────
    plan_requirements: PlanRequirements | None
    primary_activity: ActivityProposal | None
    family_activities: list[FamilyActivity]
    meal_plan: RestaurantRecommendation | None

    # ── History (append reducers) ─────────────────────────────────────────────
    # LangGraph Pattern: State reducers — append_to_list ensures concurrent
    # writers don't overwrite each other's proposals.
    proposal_history: Annotated[list[ActivityProposal], append_to_list]

    # ── Multi-agent verdicts (merge reducer) ──────────────────────────────────
    # LangGraph Pattern: merge_verdicts replaces verdicts by agent_name,
    # enabling safe concurrent writes from all 4 parallel review agents.
    current_verdicts: Annotated[list[AgentVerdict], merge_verdicts]

    # ── External data ─────────────────────────────────────────────────────────
    weather_data: object | None  # WeatherForecast — avoid circular import
    route_data: dict[str, object] | None  # keys: "home_to_activity", "activity_to_restaurant", "restaurant_to_home"
    safety_data: dict | None  # vestigial — no agent writes this; keep for forward compat

    # ── Execution control ─────────────────────────────────────────────────────
    iteration_count: int
    max_iterations: int
    current_phase: Literal["drafting", "reviewing", "revising", "validating", "human_review", "completed"]
    rejection_context: str | None
    pending_constraints: list[str]  # mid-flight constraints from WebSocket

    # NOTE: model_router, tool_registry, and config are NOT stored in state.
    # They are non-JSON-serializable and would be lost on checkpoint round-trips.
    # They are injected into each node call by the _inject_runtime wrapper in
    # graph/planner.py via closure, so agents can still do state["model_router"].

    # ── Negotiation log (append reducer) ─────────────────────────────────────
    # LangGraph Pattern: append_log adds timestamps; full log written on --debug.
    negotiation_log: Annotated[list[str], append_log]

    # ── Human interaction ─────────────────────────────────────────────────────
    human_feedback: str | None
    human_rejection_count: int

    # ── Output artifacts ─────────────────────────────────────────────────────
    output_html: str | None
    output_markdown: str | None
    backup_activity: ActivityProposal | None  # generated by synthesizer (task 5.12)
    # keys: data source names (e.g. "weather", "route")
    # values: display strings (e.g. "(est.)", "(3hr cache)")
    output_confidence_labels: dict[str, str] | None
